version: '3.8'

services:
  # Simple SSL termination proxy
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"  
      - "443:443"
    volumes:
      - ./nginx/simple.conf:/etc/nginx/conf.d/default.conf:ro
      - ./ssl/server.crt:/etc/ssl/server.crt:ro
      - ./ssl/server.key:/etc/ssl/server.key:ro
    depends_on:
      - web
    networks:
      - cnc-network
    restart: unless-stopped

  # Web Application (Next.js)
  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile  
    environment:
      - NODE_ENV=production
      - SENTRY_SUPPRESS_INSTRUMENTATION_FILE_WARNING=1
      - SENTRY_SUPPRESS_GLOBAL_ERROR_HANDLER_FILE_WARNING=1
      - NEXT_PUBLIC_SUPABASE_URL=http://localhost:5432
      - NEXT_PUBLIC_SUPABASE_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6ImFub24iLCJleHAiOjE5ODM4MTI5OTZ9.CRXP1A7WOeoJeXxjNni43kdQwgnWNReilDMblYTn_I0
      - NEXT_PUBLIC_API_URL=https://app.frigate.ai/api
      - SUPABASE_SERVICE_ROLE_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImV4cCI6MTk4MzgxMjk5Nn0.EGIM96RAZx35lJzdJsyH-qQwv8Hdp7fsn3W0YpN81IU
      - JWT_SECRET=cnc-quote-jwt-secret-key-2024-production-ready
    depends_on:
      - api
      - supabase
    networks:
      - cnc-network
    restart: unless-stopped

  # API Service (NestJS)
  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    environment:
      - NODE_ENV=production
      - PORT=3001
      - DATABASE_URL=postgresql://postgres:postgres@supabase:5432/postgres
      - SUPABASE_URL=https://app.frigate.ai/db
      - SUPABASE_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6ImFub24iLCJleHAiOjE5ODM4MTI5OTZ9.CRXP1A7WOeoJeXxjNni43kdQwgnWNReilDMblYTn_I0
      - SUPABASE_SERVICE_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImV4cCI6MTk4MzgxMjk5Nn0.EGIM96RAZx35lJzdJsyH-qQwv8Hdp7fsn3W0YpN81IU
      - SUPABASE_SERVICE_ROLE_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImV4cCI6MTk4MzgxMjk5Nn0.EGIM96RAZx35lJzdJsyH-qQwv8Hdp7fsn3W0YpN81IU
      - REDIS_URL=redis://redis:6379
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - CAD_SERVICE_URL=http://cad-service:10001
      - PAYPAL_CLIENT_ID=your_paypal_client_id
      - PAYPAL_CLIENT_SECRET=your_paypal_client_secret
      - PAYPAL_ENV=live
      - SMTP_HOST=smtp.gmail.com
      - SMTP_PORT=587
      - SMTP_USER=placeholder@example.com
      - SMTP_PASS=placeholder
      - SLACK_BOT_TOKEN=xoxb-placeholder
      - APP_URL=https://app.frigate.ai
      - JWT_SECRET=cnc-quote-jwt-secret-key-2024-production-ready
      - ALLOWED_ORIGINS=https://app.frigate.ai
      - APP_NAME=CNC Quote
    depends_on:
      - supabase
      - redis
    networks:
      - cnc-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3001/v1/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # CAD Service (FastAPI)
  cad-service:
    build:
      context: .
      dockerfile: apps/cad-service/Dockerfile
    environment:
      - PYTHONUNBUFFERED=1
      - SUPABASE_URL=https://app.frigate.ai/db
      - SUPABASE_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImV4cCI6MTk4MzgxMjk5Nn0.EGIM96RAZx35lJzdJsyH-qQwv8Hdp7fsn3W0YpN81IU
      - SUPABASE_SERVICE_ROLE_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImV4cCI6MTk4MzgxMjk5Nn0.EGIM96RAZx35lJzdJsyH-qQwv8Hdp7fsn3W0YpN81IU
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - API_URL=http://api:3001
    depends_on:
      - supabase
      - redis
    networks:
      - cnc-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:10001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Supabase (PostgreSQL + Supabase services)
  supabase:
    image: supabase/postgres:15.1.0.147
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - supabase_data:/var/lib/postgresql/data
      - ./supabase/config.toml:/etc/supabase/config.toml:ro
    networks:
      - cnc-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis
  redis:
    image: redis:7-alpine
    volumes:
      - redis_data:/data
    networks:
      - cnc-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # RedisInsight (Web UI for Redis) - Optional
  redisinsight:
    image: redis/redisinsight:latest
    ports:
      - "8002:8001"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
    networks:
      - cnc-network
    restart: unless-stopped

volumes:
  supabase_data:
  redis_data:

networks:
  cnc-network:
    driver: bridge