services:
  - type: web
    name: cnc-quote-web
    env: node
    buildCommand: cd apps/web && pnpm install && pnpm build
    startCommand: cd apps/web && pnpm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_SUPABASE_URL
        sync: false
      - key: NEXT_PUBLIC_SUPABASE_ANON_KEY
        sync: false
      - key: NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY
        sync: false
      - key: NEXT_PUBLIC_API_URL
        sync: false
      - key: NEXT_PUBLIC_SENTRY_DSN
        sync: false
      - key: NEXT_PUBLIC_POSTHOG_KEY
        sync: false

  - type: web
    name: cnc-quote-api
    env: node
    buildCommand: cd apps/api && pnpm install && pnpm build
    startCommand: cd apps/api && pnpm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_WEBHOOK_SECRET
        sync: false
      - key: SENTRY_DSN
        sync: false
      - key: POSTHOG_API_KEY
        sync: false
      - key: PORT
        value: 3000

  - type: web
    name: cnc-quote-cad
    env: docker
    dockerfilePath: ./apps/cad-service/Dockerfile
    envVars:
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false
      - key: PORT
        value: 3001
