# Render.com Free Plan Configuration for CNC Quote Platform
version: "1"
services:
  # Next.js Web Application
  - type: web
    name: cnc-quote-web
    env: node
    repo: https://github.com/seovimalraj/cnc-quote
    plan: free
    region: oregon
    buildCommand: |
      set -e
      echo "Installing pnpm..."
      npm install -g pnpm@8.15.4

      echo "Installing dependencies..."
      pnpm install --no-frozen-lockfile

      echo "Building shared package..."
      cd packages/shared && pnpm install --no-frozen-lockfile && pnpm build

      echo "Building web app..."
      cd ../apps/web
      pnpm install --no-frozen-lockfile
      SKIP_ENV_VALIDATION=true NODE_ENV=production pnpm build
    startCommand: cd apps/web && pnpm start
    healthCheckPath: /
    autoDeployTrigger: commit
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_VERSION
        value: "20.15.1"
      - key: NEXT_PUBLIC_SUPABASE_URL
        sync: false
      - key: NEXT_PUBLIC_SUPABASE_ANON_KEY
        sync: false
      - key: NEXT_PUBLIC_API_URL
        sync: false
      - key: NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY
        sync: false
      - key: NEXT_PUBLIC_APP_URL
        sync: false
      - key: PORT
        value: "3000"

  # NestJS API Service
  - type: web
    name: cnc-quote-api
    env: node
    repo: https://github.com/seovimalraj/cnc-quote
    plan: free
    region: oregon
    buildCommand: |
      set -e
      echo "Installing pnpm..."
      npm install -g pnpm@8.15.4

      echo "Installing dependencies..."
      pnpm install --no-frozen-lockfile

      echo "Building shared package..."
      cd packages/shared && pnpm install --no-frozen-lockfile && pnpm build

      echo "Building API..."
      cd ../apps/api && pnpm install --no-frozen-lockfile && ./build-ignore-errors.sh
    startCommand: cd apps/api && pnpm prod
    healthCheckPath: /health
    autoDeployTrigger: commit
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_VERSION
        value: "20.15.1"
      - key: PORT
        value: "10000"
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false
      - key: SUPABASE_SERVICE_KEY
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_WEBHOOK_SECRET
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: REDIS_URL
        sync: false

  # Python CAD Service
  - type: web
    name: cnc-quote-cad
    env: python
    repo: https://github.com/seovimalraj/cnc-quote
    plan: free
    region: oregon
    buildCommand: |
      set -e
      cd apps/cad-service
      pip install -r requirements.txt
    startCommand: cd apps/cad-service && python main.py
    healthCheckPath: /docs
    autoDeployTrigger: commit
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: PORT
        value: "8001"

  # Redis for background jobs
  - type: redis
    name: cnc-quote-redis
    plan: free
    region: oregon
    maxmemoryPolicy: noeviction
    ipAllowList: []
