name: cad-service
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pythonocc-core=7.7.0
  - occt=7.7.2
  - pip
  - pip:
    - fastapi>=0.104.0
    - uvicorn>=0.23.2
    - pydantic>=2.4.2
    - celery>=5.3.4
    - redis>=5.0.1
    - python-multipart>=0.0.6
    - numpy>=1.26.0
    - httpx>=0.25.0
