// Static seed catalog data (initial) - lightweight approximation of industrial catalog
// In production this would come from DB + admin CMS. Version bump when materially changed.
import { CatalogSnapshot } from './catalog.types';

export const CATALOG_SNAPSHOT: CatalogSnapshot = {
  version: '2025-01-01.001',
  generated_at: new Date().toISOString(),
  materials: [
    {
      id: 'mat-al-6061-t6',
      code: 'ALU-6061-T6',
      name: 'Aluminum 6061-T6',
      category: 'metal',
      subcategory: 'aluminum',
      density_g_cm3: 2.7,
      cost_per_kg: 6.2,
      machining_factor: 0.9,
      min_wall_mm: 1.5,
      recyclable: true,
      active: true
    },
    {
      id: 'mat-al-7075-t6',
      code: 'ALU-7075-T6',
      name: 'Aluminum 7075-T6',
      category: 'metal',
      subcategory: 'aluminum',
      density_g_cm3: 2.81,
      cost_per_kg: 11.5,
      machining_factor: 1.05,
      min_wall_mm: 1.8,
      recyclable: true,
      active: true
    },
    {
      id: 'mat-ss-304',
      code: 'SS-304',
      name: 'Stainless Steel 304',
      category: 'metal',
      subcategory: 'stainless',
      density_g_cm3: 8.0,
      cost_per_kg: 7.9,
      machining_factor: 1.2,
      min_wall_mm: 1.5,
      recyclable: true,
      active: true
    },
    {
      id: 'mat-abs-black',
      code: 'ABS-BLACK',
      name: 'ABS Plastic (Black)',
      category: 'plastic',
      subcategory: 'abs',
      density_g_cm3: 1.04,
      cost_per_kg: 3.1,
      machining_factor: 0.75,
      min_wall_mm: 2.0,
      recyclable: false,
      active: true
    }
  ],
  finishes: [
    {
      id: 'fin-anodize-clear',
      code: 'ANODIZE-CLEAR',
      name: 'Clear Anodize',
      type: 'surface',
      process_family: 'anodize',
      cost_per_part: 2.5,
      cost_per_area_cm2: 0.004,
      prep_time_min: 10,
      rate_cm2_min: 20,
      typical_lead_time_days: 3,
      lead_time_add_days: 2,
      compatible_material_categories: ['metal'],
      active: true
    },
    {
      id: 'fin-bead-blast',
      code: 'BEAD-BLAST',
      name: 'Bead Blast Finish',
      type: 'surface',
      process_family: 'bead-blast',
      cost_per_part: 1.5,
      cost_per_area_cm2: 0.003,
      prep_time_min: 5,
      rate_cm2_min: 18,
      typical_lead_time_days: 2,
      lead_time_add_days: 1,
      compatible_material_categories: ['metal', 'plastic'],
      active: true
    }
  ],
  processes: [
    {
      id: 'proc-cnc-mill-3ax',
      code: 'CNC-MILL-3AX',
      name: 'CNC Milling 3-Axis',
      family: 'cnc',
      axis_capability: 3,
      max_part_envelope_mm: [600, 400, 300],
      tolerance_classes: ['ISO2768-m', 'ISO2768-f'],
      base_lead_time_days: 5,
      rush_lead_time_days: 2,
      complexity_weight: 1,
      active: true
    },
    {
      id: 'proc-cnc-mill-4ax',
      code: 'CNC-MILL-4AX',
      name: 'CNC Milling 4-Axis',
      family: 'cnc',
      axis_capability: 4,
      max_part_envelope_mm: [500, 400, 300],
      tolerance_classes: ['ISO2768-m', 'ISO2768-f'],
      base_lead_time_days: 6,
      rush_lead_time_days: 3,
      complexity_weight: 1.15,
      active: true
    },
    {
      id: 'proc-cnc-mill-5ax',
      code: 'CNC-MILL-5AX',
      name: 'CNC Milling 5-Axis',
      family: 'cnc',
      axis_capability: 5,
      max_part_envelope_mm: [400, 400, 300],
      tolerance_classes: ['ISO2768-f', 'ASMEB89-precision'],
      base_lead_time_days: 7,
      rush_lead_time_days: 3,
      complexity_weight: 1.25,
      active: true
    },
    {
      id: 'proc-cnc-turn-2ax',
      code: 'CNC-TURN-2AX',
      name: 'CNC Turning 2-Axis',
      family: 'cnc',
      axis_capability: 2,
      max_part_envelope_mm: [300, 300, 300],
      tolerance_classes: ['ISO2768-m', 'ISO2768-f'],
      base_lead_time_days: 4,
      rush_lead_time_days: 2,
      complexity_weight: 0.9,
      active: true
    },
    {
      id: 'proc-cnc-turn-multi',
      code: 'CNC-TURN-MULTI',
      name: 'CNC Turning Multi-Axis',
      family: 'cnc',
      axis_capability: 4,
      max_part_envelope_mm: [300, 300, 300],
      tolerance_classes: ['ISO2768-f', 'ASMEB89-precision'],
      base_lead_time_days: 6,
      rush_lead_time_days: 3,
      complexity_weight: 1.1,
      active: true
    },
    {
      id: 'proc-sheet-laser',
      code: 'SHEET-LASER',
      name: 'Sheet Metal Laser Cut',
      family: 'sheet_metal',
      max_part_envelope_mm: [1500, 3000, 25],
      tolerance_classes: ['ISO2768-m'],
      base_lead_time_days: 4,
      rush_lead_time_days: 2,
      complexity_weight: 0.8,
      active: true
    },
    {
      id: 'proc-sheet-punch',
      code: 'SHEET-PUNCH',
      name: 'Sheet Metal Punch',
      family: 'sheet_metal',
      max_part_envelope_mm: [1500, 3000, 25],
      tolerance_classes: ['ISO2768-m'],
      base_lead_time_days: 3,
      rush_lead_time_days: 1,
      complexity_weight: 0.7,
      active: true
    },
    {
      id: 'proc-sheet-bend',
      code: 'SHEET-BEND',
      name: 'Sheet Metal Bend/Form',
      family: 'sheet_metal',
      max_part_envelope_mm: [1500, 3000, 25],
      tolerance_classes: ['ISO2768-m'],
      base_lead_time_days: 5,
      rush_lead_time_days: 2,
      complexity_weight: 0.9,
      active: true
    },
    {
      id: 'proc-inj-mold-al',
      code: 'INJ-MOLD-AL',
      name: 'Injection Molding Aluminum Tool',
      family: 'injection_molding',
      max_part_envelope_mm: [200, 200, 100],
      tolerance_classes: ['ISO2768-m'],
      base_lead_time_days: 15,
      rush_lead_time_days: 10,
      complexity_weight: 2.0,
      active: true
    },
    {
      id: 'proc-inj-mold-steel',
      code: 'INJ-MOLD-STEEL',
      name: 'Injection Molding Steel Tool',
      family: 'injection_molding',
      max_part_envelope_mm: [200, 200, 100],
      tolerance_classes: ['ISO2768-m', 'ISO2768-f'],
      base_lead_time_days: 20,
      rush_lead_time_days: 12,
      complexity_weight: 2.2,
      active: true
    },
    {
      id: 'proc-cast-sand',
      code: 'CAST-SAND',
      name: 'Sand Casting',
      family: 'casting',
      max_part_envelope_mm: [500, 500, 500],
      tolerance_classes: ['ISO2768-c'],
      base_lead_time_days: 10,
      rush_lead_time_days: 5,
      complexity_weight: 1.3,
      active: true
    },
    {
      id: 'proc-cast-investment',
      code: 'CAST-INVESTMENT',
      name: 'Investment Casting',
      family: 'casting',
      max_part_envelope_mm: [300, 300, 300],
      tolerance_classes: ['ISO2768-m', 'ISO2768-f'],
      base_lead_time_days: 12,
      rush_lead_time_days: 7,
      complexity_weight: 1.5,
      active: true
    },
    {
      id: 'proc-cast-die',
      code: 'CAST-DIE',
      name: 'Die Casting',
      family: 'casting',
      max_part_envelope_mm: [400, 400, 300],
      tolerance_classes: ['ISO2768-m'],
      base_lead_time_days: 14,
      rush_lead_time_days: 8,
      complexity_weight: 1.6,
      active: true
    },
    {
      id: 'proc-3dp-fdm',
      code: '3DP-FDM',
      name: '3D Printing FDM',
      family: 'finishing',
      max_part_envelope_mm: [200, 200, 200],
      tolerance_classes: ['ISO2768-c'],
      base_lead_time_days: 2,
      rush_lead_time_days: 1,
      complexity_weight: 0.5,
      active: true
    },
    {
      id: 'proc-3dp-sla',
      code: '3DP-SLA',
      name: '3D Printing SLA',
      family: 'finishing',
      max_part_envelope_mm: [150, 150, 150],
      tolerance_classes: ['ISO2768-m'],
      base_lead_time_days: 3,
      rush_lead_time_days: 1,
      complexity_weight: 0.6,
      active: true
    },
    {
      id: 'proc-3dp-sls',
      code: '3DP-SLS',
      name: '3D Printing SLS',
      family: 'finishing',
      max_part_envelope_mm: [300, 300, 300],
      tolerance_classes: ['ISO2768-m'],
      base_lead_time_days: 4,
      rush_lead_time_days: 2,
      complexity_weight: 0.7,
      active: true
    },
    {
      id: 'proc-urethane-cast',
      code: 'URETHANE-CAST',
      name: 'Urethane Casting',
      family: 'finishing',
      max_part_envelope_mm: [400, 400, 200],
      tolerance_classes: ['ISO2768-m'],
      base_lead_time_days: 8,
      rush_lead_time_days: 4,
      complexity_weight: 1.2,
      active: true
    }
  ],
  machines: [
    {
      id: 'mc-cnc-3ax-small',
      code: 'M-CNC-3AX-SMALL',
      process_code: 'CNC-MILL-3AX',
      description: 'Entry 3-axis VMC',
      max_envelope_mm: [400, 300, 250],
      spindle_power_kw: 11,
      tool_count: 24,
      hourly_rate: 55,
      setup_time_min: 35,
      min_order_value: 50,
      min_order_qty: 1,
      overhead_pct: 0.18,
      margin_pct: 0.25,
      active: true
    },
    {
      id: 'mc-cnc-5ax-mid',
      code: 'M-CNC-5AX-MID',
      process_code: 'CNC-MILL-5AX',
      description: 'Mid-size 5-axis machining center',
      max_envelope_mm: [350, 350, 300],
      spindle_power_kw: 22,
      tool_count: 60,
      hourly_rate: 95,
      setup_time_min: 50,
      min_order_value: 120,
      min_order_qty: 1,
      overhead_pct: 0.22,
      margin_pct: 0.28,
      active: true
    },
    {
      id: 'mc-laser-sheet',
      code: 'M-SHEET-LASER-STD',
      process_code: 'SHEET-LASER',
      description: 'Industrial fiber laser',
      max_envelope_mm: [1500, 3000, 25],
      hourly_rate: 65,
      setup_time_min: 20,
      min_order_value: 40,
      min_order_qty: 1,
      overhead_pct: 0.15,
      margin_pct: 0.22,
      active: true
    }
  ]
};

export type { CatalogSnapshot };
