name: mock-scan
on:
  pull_request:
    types: [opened, synchronize]
jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: node tools/mock_scan/index.mjs
      - name: Fail on admin-surface mocks
        run: |
          node <<'EOF'
          import fs from 'node:fs';
          const data = JSON.parse(fs.readFileSync('audit/mock-kill-list.json', 'utf8'));
          const offenders = data.results.filter((r) => r.isAdminSurface && (r.byName || r.hits.length));
          if (offenders.length) {
            console.error('Admin mocks detected:\n' + offenders.map((r) => ` - ${r.file}`).join('\n'));
            process.exit(1);
          }
          EOF
